# Server configurations
server:
  servlet:
    context-path: /mercado-libre

# Login configuration
logging:
  level:
    root: INFO
    org.springdoc: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    com.mercadolibre.coupon: DEBUG

# Actuator configuration
management:
  endpoints:
    caches:
      enabled: true
    web:
      exposure:
        include: health, info, caches, circuitbreakers
  endpoint:
    health:
      show-details: always

# Swagger configurations
springdoc:
  api-docs:
    enabled: true
    path: /swagger-api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Spring configurations
spring:
  application:
    name: coupon
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# Application configuration
application:
  default-limit: 5
  conversion-value: 100

cron-task:
  cache:
    api-call-refresh: 0 */10 * * * ?

# Services configurations
services:
  mercado-libre:
    paths:
      fetch-product: /items/{id}
      fetch-products: /items
      fetch-country: /country/{id}
      fetch-countries: /sites

# Resilience configuration
resilience4j:
  circuitbreaker:
    instances:
      # Entry-point
      couponRedeemed:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        maxWaitDurationInHalfOpenState: 3m
      couponProducts:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        maxWaitDurationInHalfOpenState: 3m
  ratelimiter:
    instances:
      # Entry-point
      couponRedeemed:
        limit-for-period: 120
        limit-refresh-period: 1m
        timeout-duration: 0
      couponProducts:
        limit-for-period: 120
        limit-refresh-period: 1m
        timeout-duration: 0
  retry:
    instances:
      # Entry-point
      couponRedeemed:
        max-attempts: 3
        wait-duration: 1s
      couponProducts:
        max-attempts: 3
        wait-duration: 1s
      # Output-point
      feignCountryClient:
        max-attempts: 3
        wait-duration: 1s
      feignProductClient:
        max-attempts: 3
        wait-duration: 1s
      repositoryCouponClient:
        max-attempts: 3
        wait-duration: 1s